config/routes.rb
Rails.application.routes.draw do
  resources :user_details
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "user_details#index"
    end
	end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_attached_file :aadhar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :aadhar, content_type: /\Aimage\/.*\z/

  validates_presence_of :birth_date, :father_name, :children, :aadhar 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birth_date, :father_name, :children, :aadhar])
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order("created_at desc").page(params[:page]).per(5)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
  end

  def update
    respond_to do |format|
      if @user.update(user_details_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :aadhar, :birth_date, :father_name, :children)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hindustani</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',  integrity:'sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm', crossorigin:'anonymous' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-beta.1//js/froala_editor.pkgd.min.js"></script>
    <%= javascript_include_tag 'https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main_content">
      <div id="header">
        <% if user_signed_in? %>
          <div class="buttons">
            <strong><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></strong>
          </div>
        <% end %>
      </div>
      <% flash.each  do |name, msg| %>
        <div>
          <strong><%= content_tag(:div, msg, class: "alert alert-info") %></strong>
        </div>
      <% end %>
        <br><%= yield %>
    </div>
  </body>
</html>

app/views/user_details/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/user_details/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/user_details/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/user_details/index.html.erb
<h1>Users</h1>
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th>Name</th>
				<th>Birth Date</th>
				<th>Father name</th>
				<th>Children</th>
        <th>Aadhar</th>
        <th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |object| %>
				<tr>
					<td><%= object.name %></td>
					<td><%= object.birth_date&.strftime("%d-%b-%Y") %></td>
					<td><%= object.father_name %></td>
          <td><%= object.children %></td>
          <td>
            <a href="<%= object.aadhar %>" id="aadhar_image" width="100">
              <img class="img-thumbnail" src="<%= object.aadhar %>" width="50"/>
            </a>
          </td>
					<td>
            <%= link_to 'Show', user_detail_path(object) %>
					  <%= link_to 'Destroy', user_detail_path(object) , method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
				</tr>
			<% end %>
		</tbody>
	</table>

  <%= paginate @users, :page_links => false %>

app/views/user_details/index.js.erb
<%= smart_listing_update :users %>

app/views/user_details/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/user_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birth Date:</strong>
  <%= @user.birth_date.strftime("%d-%b-%Y") %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @user.father_name %>
</p>

<p>
  <strong>children name:</strong>
  <%= @user.children %>
</p>

<p>
  <strong>Aadhar:</strong>
  <%= image_tag @user.aadhar.url(:thumb)%>
</p>


<%= link_to 'Back', user_details_path %>

app/views/user_details/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>